name: echo_guide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.0.0
  google_sign_in: ^6.0.0
  cloud_firestore: ^4.0.0
  flutter_tts: ^4.0.2
  speech_to_text: ^7.1.0
  geolocator: ^14.0.2
  audioplayers: ^6.0.0
  provider: ^6.1.0
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.10.0
  google_maps_flutter_android: ^2.16.2
  location: ^6.0.0
  vibration: ^1.8.4
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  http: ^1.2.1
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome.png
    - assets/audio/
    - assets/ambient/
    