name: echo_guide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  google_sign_in: ^6.2.0
  cloud_firestore: ^5.6.11
  flutter_tts: ^4.0.2
  speech_to_text: ^7.1.0
  geolocator: ^14.0.2
  audioplayers: ^6.0.0
  provider: ^6.1.0
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.10.0
  google_maps_flutter_android: ^2.16.2
  location: ^8.0.1
  vibration: ^3.1.3
  permission_handler: ^12.0.1
  connectivity_plus: ^6.0.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  http: ^1.4.0
  flutter_local_notifications: ^19.3.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/welcome.png
    - assets/audio/
    - assets/ambient/
    