// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdxprwaMvvIq6oXdiDonOGe8YvCNmrC38',
    appId: '1:536088247858:android:81dd680e670b0de15e462b',
    messagingSenderId: '536088247858',
    projectId: 'mernapp-6e488',
    storageBucket: 'mernapp-6e488.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCidMmKETDIkQsFj0xegLgrVLMy--NxLL4',
    appId: '1:536088247858:web:d5d6caa4279c95b15e462b',
    messagingSenderId: '536088247858',
    projectId: 'mernapp-6e488',
    authDomain: 'mernapp-6e488.firebaseapp.com',
    storageBucket: 'mernapp-6e488.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKWUxwqpyx1KncjiMDmJz5BfVCU9m1a5Y',
    appId: '1:536088247858:web:361e7040eb5130f75e462b',
    messagingSenderId: '536088247858',
    projectId: 'mernapp-6e488',
    authDomain: 'mernapp-6e488.firebaseapp.com',
    storageBucket: 'mernapp-6e488.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmfEFOCXJwR6prUuF07LIFni2IKY7wQlI',
    appId: '1:536088247858:ios:feb87dcfd358611f5e462b',
    messagingSenderId: '536088247858',
    projectId: 'mernapp-6e488',
    storageBucket: 'mernapp-6e488.appspot.com',
    iosClientId: '536088247858-1dn84fthik1tv1gias8jq21quc8qa8j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.echoGuide',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmfEFOCXJwR6prUuF07LIFni2IKY7wQlI',
    appId: '1:536088247858:ios:feb87dcfd358611f5e462b',
    messagingSenderId: '536088247858',
    projectId: 'mernapp-6e488',
    storageBucket: 'mernapp-6e488.appspot.com',
    iosClientId: '536088247858-1dn84fthik1tv1gias8jq21quc8qa8j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.echoGuide',
  );

}